var memes = [
    {
        image: "Cheapest.jpg",
        title: "Mexican Word 1",
        category: "Mexican Word of the Day",
        easterEgg: false,
        meme_id: '1',
    },
    {
        image: "liver.jpg",
        title: "Mexican Word 2",
        category: "Mexican Word of the Day",
        easterEgg: false,
        meme_id: '2',
    },
    {
        image: "blueberry.jpg",
        title: "Mexican Word 3",
        category: "Mexican Word of the Day",
        easterEgg: false,
        meme_id: '3',
    },
    {
        image: "ring.jpg",
        title: "Jordan memes",
        category: "Mecheal Jordan memes",
        easterEgg: false,
        meme_id: '4',
    },
    {
        image: "shoes.jpg",
        title: "Jordan memes",
        category: "Mecheal Jordan memes",
        easterEgg: false,
        meme_id: '5',
    },
    {
        image: "fortnite.jpg",
        title: "Jordan memes",
        category: "Mecheal Jordan memes",
        easterEgg: false,
        meme_id: '6',
    },
    {
        image: "miracle.jpg",
        title: "NFL memes",
        category: "NFL player memes",
        easterEgg: false,
        meme_id: '7',
    },
    {
        image: "download.jpg",
        title: "NFL memes",
        category: "NFL player memes",
        easterEgg: false,
        meme_id: '8',
    },
    { 
        image: "Tom Brady.jpg",
        title: "NFL memes",
        category: "NFL player memes",
        easterEgg: false,
        meme_id: '9',
    },
    {
        image: "Melo.jpg",
        title: "NBA memes",
        category: "NBA player memes",
        easterEgg: false,
        meme_id: '10',
    },
    {
        image: "NBA.jpg",
        title: "NBA memes",
        category: "NBA player memes",
        easterEgg: false,
        meme_id: '11',
    },
    {
        image: "NBaby Face.jpg",
        title: "NBA memes",
        category: "NBA player memes",
        easterEgg: false,
        meme_id: '12',
    },
    {
        image: "Colon meme.jpg",
        title: "MLB memes",
        category: "MLB player memes",
        easterEgg: false,
        meme_id: '13',
    },
    {
        image: "Fat kid.jpg",
        title: "MLB memes",
        category: "MLB player memes",
        easterEgg: false,
        meme_id: '14',        
    },
    {
        image: "Cubs.jpg",
        title: "MLB memes",
        category: "MLB player memes",
        easterEgg: false,
        meme_id: '15',   
    },
    {
        image: "Phatworm.jpg",
        title: "You vs the guy she told you not to worry about memes",
        category: "You vs the guy she told you not to worry about memes",
        easterEgg: true,
        meme_id: '16',   
    },
    {
        image: "The Rock.jpg",
        title: "You vs the guy she told you not to worry about memes",
        category: "You vs the guy she told you not to worry about memes",
        easterEgg: false,
        meme_id: '17',   
    },
    {
        image: "Zac.jpg",
        title: "You vs the guy she told you not to worry about memes",
        category: "You vs the guy she told you not to worry about memes",
        easterEgg: false,
        meme_id: '18',   
    },
    {
        image: "Apple.jpg",
        title: "You vs the guy she told you not to worry about memes",
        category: "You vs the guy she told you not to worry about memes",
        easterEgg: false,
        meme_id: '19',   
    },
    {
        image: "Barney.jpg",
        title: "You vs the guy she told you not to worry about memes",
        category: "You vs the guy she told you not to worry about memes",
        easterEgg: false,
        meme_id: '20', 
    },


    
];